import React from "react";
import Notes from "./Notes";

export default function Main() {
  return (
    <div className="main">
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content=" quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit acing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="pisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use this?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
      <Notes title="How to use is?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium libero voluptates magnam, ducimus pariatur ipsam nostrum! Delectus ratione earum quisquam ipsam perferendis reiciendis pariatur quibusdam magni aut nesciunt, suscipit ullam rerum quidem, nulla incidunt ipsa reprehenderit, minima modi quod perspiciatis!" />
    </div>
  );
}
